### ISSUE TITLE
Can this work be extended to multi-person gesture recognition？

### ISSUE THREAD

**Issue by xudif** [rongtuech/handbodypose#2]
So Far I have trained the network with my own dataset and achieved good result. Good job! But I found that the the network can only be used for one person’s gesture recognition. What method can be used to extend it to multi-person gesture recognition?

**Comment by rongtuech** [comment]
Yes, of course, the base model (lightweight-openpose) can be used for multi people. The inference code is not limited to this purpose.
Currently, to accelerate the inference process with optical flow, I limit it to one person. It can be easily modified for multi people.
